/*
 * Microservices
 * Profile management microservice which will allow query, create, update, delete of profiles 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: manishsinghal.m@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ProfessionalDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-22T22:09:01.320Z")
public class ProfessionalDetails {
  @SerializedName("totalYearsOfExperience")
  private Integer totalYearsOfExperience = null;

  @SerializedName("primarySkill")
  private String primarySkill = null;

  @SerializedName("role/designation")
  private String roledesignation = null;

  public ProfessionalDetails totalYearsOfExperience(Integer totalYearsOfExperience) {
    this.totalYearsOfExperience = totalYearsOfExperience;
    return this;
  }

   /**
   * Get totalYearsOfExperience
   * @return totalYearsOfExperience
  **/
  @ApiModelProperty(example = "10", required = true, value = "")
  public Integer getTotalYearsOfExperience() {
    return totalYearsOfExperience;
  }

  public void setTotalYearsOfExperience(Integer totalYearsOfExperience) {
    this.totalYearsOfExperience = totalYearsOfExperience;
  }

  public ProfessionalDetails primarySkill(String primarySkill) {
    this.primarySkill = primarySkill;
    return this;
  }

   /**
   * Get primarySkill
   * @return primarySkill
  **/
  @ApiModelProperty(example = "java", required = true, value = "")
  public String getPrimarySkill() {
    return primarySkill;
  }

  public void setPrimarySkill(String primarySkill) {
    this.primarySkill = primarySkill;
  }

  public ProfessionalDetails roledesignation(String roledesignation) {
    this.roledesignation = roledesignation;
    return this;
  }

   /**
   * Get roledesignation
   * @return roledesignation
  **/
  @ApiModelProperty(example = "software engineer", required = true, value = "")
  public String getRoledesignation() {
    return roledesignation;
  }

  public void setRoledesignation(String roledesignation) {
    this.roledesignation = roledesignation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfessionalDetails professionalDetails = (ProfessionalDetails) o;
    return Objects.equals(this.totalYearsOfExperience, professionalDetails.totalYearsOfExperience) &&
        Objects.equals(this.primarySkill, professionalDetails.primarySkill) &&
        Objects.equals(this.roledesignation, professionalDetails.roledesignation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalYearsOfExperience, primarySkill, roledesignation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfessionalDetails {\n");
    
    sb.append("    totalYearsOfExperience: ").append(toIndentedString(totalYearsOfExperience)).append("\n");
    sb.append("    primarySkill: ").append(toIndentedString(primarySkill)).append("\n");
    sb.append("    roledesignation: ").append(toIndentedString(roledesignation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

